@startuml
interface GUIFactory <<Interface>> {
    # createButton(): Button
}
class MacFactory {
    + createButton(): MacButton
}
class WinFactory {
    + createButton(): WinButton
}
interface Button <<Interface>> {
    # click(): void
}
class MacButton {
    + click(): void
}
class WinButton {
    + click(): void
}

GUIFactory <|.. MacFactory :implement
GUIFactory <|.. WinFactory :implement

Button <|.. MacButton :implement
Button <|.. WinButton :implement

MacFactory --> "generate" MacButton
WinFactory --> WinButton :generate

@enduml