@startuml

class ConcreteBuilder {
    + buildPartA(): void
    + buildPartB(): void
    + buildPartC(): void
}

abstract class Builder <<abstract>> {
    + buildPartA(): void
    + buildPartB(): void
    + buildPartC(): void
}

class Director {
    + construct()
}

class Product

ConcreteBuilder ..> Product
Director o-- Builder
ConcreteBuilder <|-- Builder

@enduml